name: FirstLoginBonus
version: ${project.version}
main: com.github.mamizu0312.firstloginbonus.FirstLoginBonus
commands:
  FirstLoginBonus:
    description: firstloginbonus
    usage: /<command> on/off
    default: op
api-version: 1.13
